"""Added Friends Table

Revision ID: 1b89c5ba9692
Revises: e34828b39b8a
Create Date: 2025-03-20 19:53:40.388170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b89c5ba9692"
down_revision: Union[str, None] = "e34828b39b8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends",
        sa.Column("user_id", sa.String(length=15), nullable=False),
        sa.Column("friend_id", sa.String(length=15), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'blocked')",
            name="check_status",
        ),
        sa.ForeignKeyConstraint(["friend_id"], ["users.nox_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.nox_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "friend_id", name="unique_user_friend"),
    )
    op.create_index(op.f("ix_friends_id"), "friends", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friends_id"), table_name="friends")
    op.drop_table("friends")
    # ### end Alembic commands ###
