"""create all tables

Revision ID: ca6265b5f474
Revises:
Create Date: 2025-05-02 01:34:15.290631

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6265b5f474"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("nox_id", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nox_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "friends",
        sa.Column("user_id", sa.String(length=15), nullable=False),
        sa.Column("friend_id", sa.String(length=15), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("action_by", sa.String(length=15), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'blocked')",
            name="check_status",
        ),
        sa.ForeignKeyConstraint(["action_by"], ["users.nox_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["friend_id"], ["users.nox_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.nox_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "friend_id", name="unique_user_friend"),
    )
    op.create_index(op.f("ix_friends_id"), "friends", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friends_id"), table_name="friends")
    op.drop_table("friends")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
